version: '3.8'

services:
  web_react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teddy_web_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    networks:
      - teddy_net_fe

networks:
  teddy_net_fe:
    driver: bridge